name: run Copy_of_Ryan_LLM_Forecast_Bot.ipynb

# general info here: https://github.com/patrickloeber/python-github-action-template
# specific info about yaananth notebook runner and this workflow here: https://github.com/yaananth/run-notebook

on:
  schedule:
    - cron: '0 */6 * * *' # every 6th hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      # using the below to 
      - name: Install dependencies
        run: |
          python3 -m pip install papermill==2.4.0 ipykernel==6.15.2 nbformat==5.4.0 nbconvert==7.0.0 lxml[html_clean]

      - name: setup python
        uses: actions/setup-python@v4
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "Copy_of_Ryan_LLM_Forecast_Bot.ipynb"
          isReport: False
          poll: False # not sure what exactly this does, but seemed to cause a perpetual loop when I used it
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: ${{ RUNNER.temp }}/nb-runner
        env:
          RUNNER: ${{ toJson(runner) }}
